# Site settings
title: Franklee 的博客
header-img: img/home-bg.jpg
email: franklee33@163.com
description: "朝朝暮暮,我爱编程."
baseurl: "http://franklee33.github.io"
url: "http://franklee33.github.io"
github_username:  franklee33
qq_num: 47085711

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
