# Site settings
title: Felix33 的博客
header-img: img/home-bg.jpg
email: felix33@yeah.net
description: "朝朝暮暮,我爱编程."
baseurl: "http://felix33333.github.io/"
url: "http://felix33333.github.io"
github_username:  felix33333
qq_num: 47085711

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
