# Site settings
title: Franklee 的博客
header-img: img/home-bg.jpg
email: franklee33@163.com
description: "欢迎来到Franklee的博客"
baseurl: "/franklee33.github.io"
url: "http://franklee33.github.io"
github_username:  franklee33

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
